Repository APS-USAXS/ipython-usaxs, pull requests merged in 2019-06, with the labels that each got.

#226 mode_imaging
  profile_bluesky/startup/43-procedures.py
Labels: enhancement

#225 support additional data in custom scans
  profile_bluesky/startup/10-devices.py
  profile_bluesky/startup/32-usaxs_flyscan.py
  profile_bluesky/startup/50-plans.py
Labels: enhancement

#229 end of move completion for gap change
  profile_bluesky/startup/11-motors.py
Labels: enhancement

#233 #228 basic surveillance and archiving
  profile_bluesky/startup/usaxs_support/surveillance.py
Labels: enhancement

#235 resolve LGTM alerts
  profile_bluesky/startup/spec/spec_config.py
Labels: bug

#231 PV changes as directed
  README.md
  profile_bluesky/startup/10-devices.py
  profile_bluesky/startup/11-motors.py
  profile_bluesky/startup/29-axis_tuning.py
  profile_bluesky/startup/50-plans.py
Labels: task

#240 Examples for users to copy
  README.md
  examples/README.md
  examples/actions.txt
  examples/actions.xlsx
  examples/command_file.md
  examples/custom_loop.md
  examples/usaxs_scan_one_sample.md
  examples/use_linkam.md
Labels: documentation, enhancement

#238 (re)set default tune ranges and other settings
  profile_bluesky/startup/29-axis_tuning.py
  profile_bluesky/startup/50-plans.py
Labels: enhancement

#237 enable option to move SX & SY in preUSAXStune()
  profile_bluesky/startup/50-plans.py
Labels: enhancement

#242 user custom plans need access to ipython namespace
  examples/README.md
  examples/custom_loop.md
  examples/simple_plan.md
  examples/use_linkam.md
  profile_bluesky/startup/09-imports.py
  profile_bluesky/startup/50-plans.py
  profile_bluesky/startup/usaxs_support/surveillance.py
Labels: bug

#244 Ophyd signals for beam line diagnostics and post-mortem analyses
  profile_bluesky/startup/10-devices.py
  profile_bluesky/startup/21-aps.py
Labels: enhancement

#245 gather terms used by both SAXS & WAXS
  profile_bluesky/startup/10-devices.py
  profile_bluesky/startup/43-procedures.py
  profile_bluesky/startup/50-plans.py
Labels: task

#247 DCM_Feedback(): send email in thread
  profile_bluesky/startup/10-devices.py
Labels: task

#249 fix two errors spotted by LGTM
  profile_bluesky/startup/22-amplifiers.py
  profile_bluesky/startup/25-alta.py
Labels: bug

#243 plan: tune guard slits
  profile_bluesky/startup/09-imports.py
  profile_bluesky/startup/11-motors.py
  profile_bluesky/startup/29-axis_tuning.py
  profile_bluesky/startup/51-tune_guard_slits.py
  profile_bluesky/startup/60-metadata.py
Labels: enhancement

#260 fixes #257
  profile_bluesky/startup/22-amplifiers.py
  profile_bluesky/startup/29-axis_tuning.py
  profile_bluesky/startup/usaxs_support/saveFlyData.py
Labels: maintenance

#263 get automatic retunes working
  profile_bluesky/startup/10-devices.py
  profile_bluesky/startup/29-axis_tuning.py
  profile_bluesky/startup/32-usaxs_flyscan.py
  profile_bluesky/startup/43-procedures.py
  profile_bluesky/startup/50-plans.py
Labels: bug, high priority

#269 play the music when BS batch ends
  profile_bluesky/startup/50-plans.py
Labels: enhancement

#272 do not fail the scan just because of updating program state
  profile_bluesky/startup/32-usaxs_flyscan.py
Labels: bug

#273 fix autoscale failure
  profile_bluesky/startup/22-amplifiers.py
Labels: bug

#278 fly scan reporting when timeouts from PyEpics
  profile_bluesky/startup/32-usaxs_flyscan.py
Labels: bug

#280 optional tune *ALWAYS BEFORE* mode change
  profile_bluesky/startup/50-plans.py
Labels: bug

#282 no baseline report before/after every plan runs
  profile_bluesky/startup/01-databroker.py
Labels: question
